# Generated by Django 5.0.1 on 2024-04-12 12:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_id', models.CharField(choices=[('Midsem test', 'Midsem test'), ('Endsem test', 'Endsem test'), ('Makeup test', 'Makeup test'), ('Retest', 'Retest')], max_length=20)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 18, 25, 7, 529739))),
                ('no_of_exams', models.IntegerField()),
                ('no_of_rooms_req', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AssignTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=25)),
                ('room_number', models.CharField(max_length=15)),
                ('no_of_students', models.IntegerField()),
                ('date_time', models.ForeignKey(default=datetime.datetime(2024, 4, 13, 18, 25, 7, 529739), on_delete=django.db.models.deletion.CASCADE, to='compapp.schedule1')),
                ('teacher1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher1', to='compapp.teacher')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher2', to='compapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
