# Generated by Django 5.0.1 on 2024-04-12 13:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignteacher',
            name='date_time',
            field=models.ForeignKey(default=datetime.datetime(2024, 4, 13, 18, 34, 59, 391206), on_delete=django.db.models.deletion.CASCADE, to='compapp.schedule1'),
        ),
        migrations.AlterField(
            model_name='schedule1',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 18, 34, 59, 391206)),
        ),
    ]
